import React,{useMemo}from'react';
type Sale={date:string;book:string;series:string;type:'Einnahme'|'Ausgabe';amount:number;units:number};
type Campaign={date:string;book?:string;series?:string;channel?:string;status?:string};
type Advice={priority:'Hoch'|'Mittel'|'Niedrig';title:string;detail:string;action:string};
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const monthKey=(d:string)=>d.slice(0,7);
export default function BusinessAdvisor(){
 const sales=read<Sale[]>('studio-sales-ledger',[]),campaigns=read<Campaign[]>('studio-marketing-pro',[]);
 const analysis=useMemo(()=>{
  const income=sales.filter(x=>x.type==='Einnahme'),byBook=new Map<string,{revenue:number;units:number;months:Map<string,number>}>(),bySeries=new Map<string,{revenue:number;units:number}>();
  for(const r of income){const b=r.book||'Ohne Titel',s=r.series||'Ohne Serie',bm=byBook.get(b)||{revenue:0,units:0,months:new Map<string,number>()};bm.revenue+=Number(r.amount)||0;bm.units+=Number(r.units)||0;bm.months.set(monthKey(r.date),(bm.months.get(monthKey(r.date))||0)+(Number(r.amount)||0));byBook.set(b,bm);const sm=bySeries.get(s)||{revenue:0,units:0};sm.revenue+=Number(r.amount)||0;sm.units+=Number(r.units)||0;bySeries.set(s,sm)}
  const books=[...byBook].map(([name,v])=>({name,...v})).sort((a,b)=>b.revenue-a.revenue),series=[...bySeries].map(([name,v])=>({name,...v})).sort((a,b)=>b.revenue-a.revenue);
  const monthly=new Map<string,number>();for(const r of income)monthly.set(monthKey(r.date),(monthly.get(monthKey(r.date))||0)+(Number(r.amount)||0));const months=[...monthly].sort(([a],[b])=>a.localeCompare(b));const recent=months.slice(-3).map(([,v])=>v),forecast=recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:0;
  const advice:Advice[]=[];
  if(!income.length)advice.push({priority:'Hoch',title:'Verkaufsdaten importieren',detail:'Es liegen noch keine Einnahmedaten vor.',action:'Im Modul KDP-Berichtsimport einen aktuellen Bericht importieren.'});
  if(books[0])advice.push({priority:'Hoch',title:`Top-Titel ausbauen: ${books[0].name}`,detail:`Der Titel führt mit ${books[0].revenue.toFixed(2)} Umsatz und ${books[0].units} Einheiten.`,action:'Fortsetzung, ergänzenden Band oder gezielte Kampagne prüfen.'});
  const weak=books.filter(b=>b.units>0).sort((a,b)=>a.revenue-b.revenue)[0];if(weak&&weak!==books[0])advice.push({priority:'Mittel',title:`Schwachen Titel prüfen: ${weak.name}`,detail:`Nur ${weak.revenue.toFixed(2)} Umsatz bei ${weak.units} Einheiten.`,action:'Cover, Beschreibung, Preis und Keywords überprüfen.'});
  if(series[0]&&series[0].name!=='Ohne Serie')advice.push({priority:'Mittel',title:`Serienchance: ${series[0].name}`,detail:`Die stärkste Serie erzielt ${series[0].revenue.toFixed(2)} Umsatz.`,action:'Nächsten Band planen und bestehende Bände gegenseitig bewerben.'});
  const active=campaigns.filter(c=>c.status==='Aktiv'||c.status==='Geplant').length;if(active===0&&income.length)advice.push({priority:'Mittel',title:'Marketing aktivieren',detail:'Es gibt keine aktive oder geplante Kampagne.',action:'Im Marketing-Pro-Modul mindestens eine Kampagne für den Top-Titel anlegen.'});
  if(months.length>=2){const prev=months.at(-2)![1],cur=months.at(-1)![1],change=prev?((cur-prev)/prev)*100:0;advice.push({priority:change<0?'Hoch':'Niedrig',title:change<0?'Umsatzrückgang abfangen':'Positiven Trend nutzen',detail:`Letzter Monatsvergleich: ${change.toFixed(1)} %.`,action:change<0?'Kampagne, Preis und Produktseite priorisiert prüfen.':'Erfolgreiche Maßnahmen dokumentieren und wiederholen.'})}
  return{books,series,months,forecast,advice,totalRevenue:income.reduce((s,r)=>s+(Number(r.amount)||0),0),totalUnits:income.reduce((s,r)=>s+(Number(r.units)||0),0)};
 },[sales,campaigns]);
 const exportJson=()=>{const payload={generatedAt:new Date().toISOString(),method:'Lokale regelbasierte Analyse; keine garantierte Prognose',...analysis};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='Business-Advisor-Bericht.json';a.click();URL.revokeObjectURL(a.href)};
 return <div><h2>KI Business Advisor</h2><p>Lokale, regelbasierte Geschäftsanalyse aus deinen Verkaufs- und Marketingdaten.</p><div className="grid"><div className="card">Gesamtumsatz<br/><b>{analysis.totalRevenue.toFixed(2)}</b></div><div className="card">Einheiten<br/><b>{analysis.totalUnits}</b></div><div className="card">3-Monats-Prognose<br/><b>{analysis.forecast.toFixed(2)}</b></div><div className="card">Empfehlungen<br/><b>{analysis.advice.length}</b></div></div><button onClick={exportJson}>Advisor-Bericht exportieren</button><h3>Priorisierte Maßnahmen</h3>{analysis.advice.map((a,i)=><div className="card" key={i}><b>{a.priority}: {a.title}</b><p>{a.detail}</p><small>{a.action}</small></div>)}<h3>Top-Bücher</h3>{analysis.books.slice(0,5).map(b=><div className="card" key={b.name}>{b.name}: {b.revenue.toFixed(2)} · {b.units} Einheiten</div>)}<p><small>Prognosen basieren auf dem Durchschnitt der letzten bis zu drei Monate. Sie sind Schätzungen und keine Erfolgsgarantie. Verschiedene Währungen werden nicht automatisch umgerechnet.</small></p></div>;
}
